
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: node:18-alpine 
    working_dir: /usr/src/app  
    volumes:
      - .:/usr/src/app  
    command: sh -c "npm install && npm start"  
    environment:
      - REDIS_HOST=redis
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGNAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  report-service:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - PGHOST=postgres
      - PGUSER=${PGUSER}
      - PGNAME=${PGNAME}
      - PGPASS=${PGPASS}
      - PGPORT=5432
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: sh -c "npm install && npm run build && node dist/src/services/reportService.js"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data: